### PR TITLE
added fields_options example in the doc

### PR DESCRIPTION
**Pull request by soyket**
added fields_options sample for developers to be able to change the title, description etc. The current doc doesn't mention this at all.

### CODE REVIEW

**Comment by rami-elementor** [comment]
Thank you for the PR.

I think the `fields_options` argument should be documented in all the group controls, not only in background group control.

**Comment by soyket** [comment]
Great. If you want, I can add it for other areas as well.

Regards,

**Comment by thallysondias** [comment]
+1

Its very anoying to discorvery fields... need to generate infinites times json exports.

**Comment by rami-elementor** [comment]
Also see https://github.com/elementor/elementor/issues/3128

**Comment by rami-elementor** [comment]
Docs added in https://github.com/elementor/elementor-developers-docs/pull/303

**Pull request closed without merging**
